---
engines:
 rubocop:
   exclude_paths:
     - database/config/engines.yml
 duplication:
   exclude_paths:
     - database/config/engines.yml
 metric:
   exclude_paths:
     - database/config/engines.yml
 coverage:
   exclude_paths:
     - database/config/engines.yml
languages:
  css:
    extensions:
      - '-css.resource'
exclude_paths:
  - '.src/docs/**'