'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Users', [
    {
      stories: `Philosophy of Education is a label applied to the study of the purpose, process, nature and ideals of education. It can be considered a branch of both philosophy and education. Education can be defined as the teaching and learning of specific skills, and the imparting of knowledge, judgment and wisdom, and is something broader than the societal institution of education we often speak of.

      Many educationalists consider it a weak and woolly field, too far removed from the practical applications of the real world to be useful. But philosophers dating back to Plato and the Ancient Greeks have given the area much thought and emphasis, and there is little doubt that their work has helped shape the practice of education over the millennia.
      
      Plato is the earliest important educational thinker, and education is an essential element in "The Republic" (his most important work on philosophy and political theory, written around 360 B.C.). In it, he advocates some rather extreme methods: removing children from their mothers' care and raising them as wards of the state, and differentiating children suitable to the various castes, the highest receiving the most education, so that they could act as guardians of the city and care for the less able. He believed that education should be holistic, including facts, skills, physical discipline, music and art. Plato believed that talent and intelligence is not distributed genetically and thus is be found in children born to all classes, although his proposed system of selective public education for an educated minority of the population does not really follow a democratic model.
      
      Aristotle considered human nature, habit and reason to be equally important forces to be cultivated in education, the ultimate aim of which should be to produce good and virtuous citizens. He proposed that teachers lead their students systematically, and that repetition be used as a key tool to develop good habits, unlike Socrates' emphasis on questioning his listeners to bring out their own ideas. He emphasized the balancing of the theoretical and practical aspects of subjects taught, among which he explicitly mentions reading, writing, mathematics, music, physical education, literature, history, and a wide range of sciences, as well as play, which he also considered important.
      
      During the Medieval period, the idea of Perennialism was first formulated by St. Thomas Aquinas in his work "De Magistro". Perennialism holds that one should teach those things deemed to be of everlasting importance to all people everywhere, namely principles and reasoning, not just facts (which are apt to change over time), and that one should teach first about people, not machines or techniques. It was originally religious in nature, and it was only much later that a theory of secular perennialism developed.
      
      During the Renaissance, the French skeptic Michel de Montaigne (1533 - 1592) was one of the first to critically look at education. Unusually for his time, Montaigne was willing to question the conventional wisdom of the period, calling into question the whole edifice of the educational system, and the implicit assumption that university-educated philosophers were necessarily wiser than uneducated farm workers, for example.`,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      stories: `"I Have a Dream" is a public speech delivered by American civil rights activist Martin Luther King Jr. during the March on Washington for Jobs and Freedom on August 28, 1963, in which he calls for an end to racism in the United States and called for civil and economic rights. Delivered to over 250,000 civil rights supporters from the steps of the Lincoln Memorial in Washington, D.C., the speech was a defining moment of the civil rights movement. 
      Beginning with a reference to the Emancipation Proclamation, which freed millions of slaves in 1863, King observes that: "one hundred years later, the Negro still is not free". Toward the end of the speech, King departed from his prepared text for a partly improvised peroration on the theme "I have a dream", prompted by Mahalia Jackson's cry: "Tell them about the dream, Martin!" In this part of the speech, which most excited the listeners and has now become its most famous, King described his dreams of freedom and equality arising from a land of slavery and hatred. Jon Meacham writes that, "With a single phrase, Martin Luther King Jr. joined Jefferson and Lincoln in the ranks of men who've shaped modern America". The speech was ranked the top American speech of the 20th century in a 1999 poll of scholars of public address. `,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      stories: `Today I Rabindranath Tagore complete eighty years of my life .As I look back on the vast stretch of years that lie behind me and see in clear perspective the history of my early development, I am struck by the change that has taken place both in my own attitude and in the psychology of my countrymen -- a change that carries within it a cause of profound tragedy.
      Our direct contact with the larger world of men was linked up with the contemporary history of the English people whom we came to know in those earlier days. It was mainly through their mighty literature that we formed our ideas with regard to these newcomers to our Indian shores. In those days the type of learning that was served out to us was neither plentiful nor diverse, nor was the spirit of scientific enquiry very much in evidence. Thus their scope being strictly limited, the educated of those days had recourse to English language and literature. Their days and nights were eloquent with the stately declamations of Burke, with Macaulay’s long-rolling sentences; discussions centered upon Shakespeare's drama and Byron's poetry and above all upon the large-hearted liberalism of the nineteenth-century English politics.
      At the time though tentative attempts were being made to gain our national independence, at heart we had not lost faith in the generosity of the English race. This belief was so firmly rooted in the sentiments of our leaders as to lead them to hope that the victor would of his own grace pave the path of freedom for the vanquished. This belief was based upon the fact that England at the time provided a shelter to all those who had to flee from persecution in their own country. Political martyrs who had suffered for the honour of their people were accorded unreserved welcome at the hands of the English.
      I was impressed by this evidence of liberal humanity in the character of the English and thus I was led to set them on the pedestal of my highest respect. This generosity in their national character had not yet been vitiated by imperialist pride. About this time, as a boy in England, I had the opportunity of listening to the speeches of John Bright, both in and outside Parliament. The large-hearted, radical liberalism of those speeches, overflowing all narrow national bounds, had made so deep an impression on my mind that something of it lingers even today, even in these days of graceless disillusionment.`,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      stories: `Sportsmanship can be conceptualized as an enduring and relatively stable characteristic or disposition such that individuals differ in the way they are generally expected to behave in sports situations. In general, sportsmanship refers to virtues such as fairness, self-control, courage, and persistence, and has been associated with interpersonal concepts of treating others and being treated fairly, maintaining self-control if dealing with others, and respect for both authority and opponents. Sportsmanship is also looked at as being the way one reacts to a sport/game/player.

      The four elements of sportsmanship are often shown being good form, the will to win, equity and fairness. All four elements are critical and a balance must be found among all four for true sportsmanship to be illustrated. These elements may also cause conflict, as a person may desire to win more than play in equity and fairness and thus resulting in a clash within the aspects of sportsmanship. This will cause problems as the person believes they are being a good sportsman, but they are defeating the purpose of this idea as they are ignoring two key components of being sportsman like. When athletes become too self-centred, the idea of sportsmanship is dismissed.
      
      Today's sporting culture, in particular the base of elite sport, places great importance on the idea of competition and winning and thus sportsmanship takes a back seat as a result. In most, if not all sports, sportsmen at the elite level make the standards on sportsmanship and no matter whether they like it or not, they are seen as leaders and role models in society.
      
      Since every sport is rule driven, the most common offence of bad sportsmanship is the act of cheating or breaking the rules to gain an unfair advantage. A competitor who exhibits poor sportsmanship after losing a game or contest is often called a "sore loser", while a competitor who exhibits poor sportsmanship after winning is typically called a "bad winner". Sore loser behavior includes blaming others for the loss, not accepting responsibility for personal actions that contributed to the defeat, reacting to the loss in an immature or improper fashion, making excuses for the defeat, and citing unfavourable conditions or other petty issues as reasons for the defeat. A bad winner acts in a shallow fashion after his or her victory, such as by gloating about his or her win, rubbing the win in the face(s) of the opponent(s), and lowering the opponent(s)'s self-esteem by constantly reminding the opponent(s) of "poor" performance in comparison (even if the opponent(s) competed well). Not showing respect to the other team is considered to being a bad sportsman and could lead to demoralizing effects; as Leslie Howe describes: "If a pitcher in baseball decides to pitch not to his maximum ability suggest that the batter is not at an adequate level, [it] could lead to the batter to have low self-confidence or worth.`,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      stories: `Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, in contrast to the natural intelligence displayed by humans and other animals. In computer science AI research is defined as the study of "intelligent agents": any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals. Colloquially, the term "artificial intelligence" is applied when a machine mimics "cognitive" functions that humans associate with other human minds, such as "learning" and "problem solving".
      The scope of AI is disputed: as machines become increasingly capable, tasks considered as requiring "intelligence" are often removed from the definition, a phenomenon known as the AI effect, leading to the quip, "AI is whatever hasn't been done yet." For instance, optical character recognition is frequently excluded from "artificial intelligence", having become a routine technology. Capabilities generally classified as AI as of 2017 include successfully understanding human speech, competing at the highest level in strategic game systems (such as chess and Go), autonomous cars, intelligent routing in content delivery network and military simulations.
      Artificial intelligence was founded as an academic discipline in 1956, and in the years since has experienced several waves of optimism, followed by disappointment and the loss of funding (known as an "AI winter"), followed by new approaches, success and renewed funding. For most of its history, AI research has been divided into subfields that often fail to communicate with each other. These sub-fields are based on technical considerations, such as particular goals (e.g. "robotics" or "machine learning"), the use of particular tools ("logic" or artificial neural networks), or deep philosophical differences. Subfields have also been based on social factors (particular institutions or the work of particular researchers). 
      The traditional problems (or goals) of AI research include reasoning, knowledge representation, planning, learning, natural language processing, perception and the ability to move and manipulate objects. General intelligence is among the field's long-term goals. Approaches include statistical methods, computational intelligence, and traditional symbolic AI. Many tools are used in AI, including versions of search and mathematical optimization, artificial neural networks, and methods based on statistics, probability and economics. The AI field draws upon computer science, mathematics, psychology, linguistics, philosophy and many others.`,
      createdAt: new Date(),
      updatedAt: new Date()
    },
  ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Users', null, {});
  }
};
